### ISSUE TITLE
PHP version compatibility

### ISSUE THREAD

**Issue by idmarinas** [kitlabs-cn/KitCryptBundle#2]
Hi:

Version `3.2.0` of your bundle is compatible with PHP version `>=5.5.9`, however version `4.0.0` of your bundle is compatible with PHP version `>= 8.0`

Isn't this a big jump?

Could it be compatible with PHP version `>=7.3`? 

I am using this version on my server and the package is not compatible with Symfony version `5.4`.

This is because of:

```php
//-- This code 
$treeBuilder = new TreeBuilder();
$rootNode = $treeBuilder->root('kit_crypt');

//-- Fixed code in your version 4.0.0
$treeBuilder = new TreeBuilder('kit_crypt');
$rootNode = $treeBuilder->getRootNode();
```

**Comment by yanfeng1012** [comment]
@idmarinas Version `4.0.1` is compatible with PHP version `>=7.3`
